[project]
name = "writing_an_interpreter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pytest>=8.3.4",
]

[tool.pytest.ini_options]
pythonpath = "src"

[tool.setuptools.package-data]
"writing_an_interpreter" = ["*.ğŸµ", "src/writing_an_interpreter/*.ğŸµ"]
